#!/bin/bash
TODAY=$(date "+%B %d, %Y")
DATE=${1:-$TODAY}
DIR="$(dirname "$(readlink `which $0`)")"
(echo "Development Log"; /usr/bin/osascript "$DIR/taskLog.applescript" "$DATE") | /usr/local/bin/dayone -d="$DATE" new
